# =============================================
# ЛОГОРИРОВАНИЕ
# =============================================
# Уровень логирования для локальной среды (переопределяет значение из application.properties)
logging.level.com.dentapinos.dataguard=DEBUG

# =============================================
# ПОДКЛЮЧЕНИЕ К БАЗАМ ДАННЫХ
# =============================================
# База данных bm (auth-service)
backup.param.databases[0].database-name=bm
backup.param.databases[0].display-name=auth-service
backup.param.databases[0].url=jdbc:mysql://localhost:3306/bm?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
backup.param.databases[0].username=root
backup.param.databases[0].password=

# База данных bm-test (test-service)
backup.param.databases[1].database-name=bm-test
backup.param.databases[1].display-name=test-service
backup.param.databases[1].url=jdbc:mysql://localhost:3306/bm-test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
backup.param.databases[1].username=root
backup.param.databases[1].password=

# База данных testdb (тестовая среда)
backup.param.databases[2].database-name=testdb
backup.param.databases[2].display-name=test-db
backup.param.databases[2].url=${MYSQL_JDBC_URL:jdbc:mysql://localhost:3306/testdb?allowPublicKeyRetrieval=true}
backup.param.databases[2].username=root
backup.param.databases[2].password=
